#!/bin/sh

#PACKAGES="go"
#pkg fetch -ydo packages/ $PACKAGES

make clean
#make CUSTOM=1 KERNCONF=BHYVE-NODEBUG BASE=/cdrom/usr/freebsd-dist PKG_STATIC=`which pkg-static` MFSROOT_MAXSIZE=256m MFSROOT_FREE_INODES=20% MFSROOT_FREE_BLOCKS=20%
#make iso CUSTOM=1 KERNCONF=BHYVE-NODEBUG BASE=/cdrom/usr/freebsd-dist PKG_STATIC=`which pkg-static` MFSROOT_MAXSIZE=256m MFSROOT_FREE_INODES=20% MFSROOT_FREE_BLOCKS=20%
make CUSTOM=1 KERNCONF=BHYVE-NODEBUG PKG_STATIC=`which pkg-static` MFSROOT_MAXSIZE=256m MFSROOT_FREE_INODES=20% MFSROOT_FREE_BLOCKS=20% MAKEOBJSRCDIR=../tmp SRC_DIR=../networking
make iso CUSTOM=1 KERNCONF=BHYVE-NODEBUG PKG_STATIC=`which pkg-static` MFSROOT_MAXSIZE=256m MFSROOT_FREE_INODES=20% MFSROOT_FREE_BLOCKS=20% MAKEOBJSRCDIR=../tmp SRC_DIR=../networking
