#!/bin/sh
# $Id$

# PROVIDE: packages
# BEFORE: LOGIN
# REQUIRE: mdinit tmp var
# KEYWORD: FreeBSD

. /etc/rc.subr

name="packages"
start_cmd="packages_start"
stop_cmd=":"

packages_start()
{
	PACKAGES=`/bin/ls -1 /packages/*.t?z 2>/dev/null`
	if /bin/test -n "$PACKAGES"; then
		cd /packages && /usr/local/sbin/pkg-static add *.t?z > /dev/null 2> /dev/null
	fi
}

load_rc_config $name
run_rc_command "$1"
