#!/bin/sh
# $Id$

# PROVIDE: packages
# BEFORE: FILESYSTEMS
# REQUIRE: mountcritlocal
# KEYWORD: FreeBSD

. /etc/rc.subr

name="mdinit"
start_cmd="mdinit_start"
stop_cmd=":"

mdinit_start()
{
	if [ -f /.usr.tar.xz ]; then
		/sbin/mdmfs -s 96M md /usr
		/rescue/xz -d -c /.usr.tar.xz | /rescue/tar -x -C / -f -
	elif [ -f /.usr.tar.bz2 ]; then
		/sbin/mdmfs -s 96M md /usr
		/rescue/bzip2 -d -c /.usr.tar.bz2 | /rescue/tar -x -C / -f -
	elif [ -f /.usr.tar.gz ]; then
		/sbin/mdmfs -s 96M md /usr
		/rescue/gzip -d -c /.usr.tar.gz | /rescue/tar -x -C / -f -
	else
		MD=`/sbin/mdconfig -a -t vnode -f /.usr.uzip`
		/sbin/mount -r /dev/${MD}.uzip /usr
	fi
}

load_rc_config $name
run_rc_command "$1"
